name: Run Katalon Tests with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  katalon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Katalon with Docker
      run: |
        docker run --rm -v "$PWD":/katalon/katalon/source:ro \
          katalonstudio/katalon:8.6.5 \
          katalonc -noSplash -runMode=console \
          -projectPath=/katalon/katalon/source/web-service-tests.prj \
          -retry=0 \
          -testSuitePath="Test Suites/TS-001" \
          -executionProfile="default" \
          -browserType="Chrome (headless)" \
          -apiKey="${{ secrets.KATALON_API_KEY }}"
